name: Update Outcomes
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 * * * *" # cada 15 min
  repository_dispatch:
    types: [update_outcomes]

jobs:
  update:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #PAra github actions nomas
      #- name: Setup Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: "3.11"
      #    cache: "pip"
      #- name: Install dependencies
      #  run: pip install requests pandas==2.2.3
      - name: Run update_outcomes
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          source ~/scanall/venv/bin/activate
          python update_outcomes.py
